# Generated by Django 4.1.2 on 2022-10-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditspreadit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateRanges',
            new_name='DateRange',
        ),
    ]
